name: Testing
on: [push]
env:
  HELM_PLUGIN_DIR: .
  SETUP: |-
    mkdir -p test/dir.yaml
    mkdir -p test/one/dir.txt

    echo a: 1 > test/foo.yaml
    echo b: 2 > test/bar.yml
    echo c: 3 > test/baz.txt
    echo d: 4 > test/one/foo.yaml
    echo e: 5 > test/one/dir.txt/foo.yaml
    echo f: 6 > test/one/fizz.txt
    echo g: 7 > test/dir.yaml/foo.enc
jobs:
  Test-Downloader-Plugin:
    runs-on: ubuntu-latest
    container: alpine/helm:3.5.4
    env:
      HELM_BIN: helm
      TEST_SCRIPT: |-
        result="$(bin/discover . . . "${path}")"
        test "$expected" == "$result" \
        || (echo "Expected:
        ${expected}
        Result:
        ${result}"; return 1)
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Establish test config hierarchy
        run: sh -c "${SETUP}"

      - name: Test default behaviour
        env:
          path: discover://test
          expected: |-
            a: 1
            b: 2
        run: sh -c "${TEST_SCRIPT}"

      - name: Test behaviour without default suffix filtering
        env:
          path: discover://test?suffix=
          expected: |-
            a: 1
            b: 2
            c: 3
        run: sh -c "${TEST_SCRIPT}"

      - name: Test recursive behaviour
        env:
          path: discover://test?recursive
          expected: |-
            a: 1
            b: 2
            d: 4
            e: 5
        run: sh -c "${TEST_SCRIPT}"

      - name: Test suffix behaviour
        env:
          path: discover://test?suffix=.txt
          expected: |-
            c: 3
        run: sh -c "${TEST_SCRIPT}"

      - name: Test recursive and suffix behaviour
        env:
          path: discover://test?recursive&suffix=.txt
          expected: |-
            c: 3
            f: 6
        run: sh -c "${TEST_SCRIPT}"

      - name: Test prefix and suffix behaviour
        env:
          path: discover://test?suffix=.txt&prefix=b
          expected: |-
            c: 3
        run: sh -c "${TEST_SCRIPT}"

      - name: Test unioned prefix and suffix behaviour
        env:
          path: discover://test?suffix=.txt&prefix=b&union
          expected: |-
            b: 2
            c: 3
        run: sh -c "${TEST_SCRIPT}"

      - name: Test recursive prefix and suffix behaviour
        env:
          path: discover://test?suffix=.txt&prefix=f&recursive
          expected: |-
            f: 6
        run: sh -c "${TEST_SCRIPT}"

      - name: Test recursive unioned prefix and suffix behaviour
        env:
          path: discover://test?union&suffix=.txt&prefix=f&recursive
          expected: |-
            a: 1
            c: 3
            d: 4
            e: 5
            f: 6
            g: 7
        run: sh -c "${TEST_SCRIPT}"

  Test-Downloader-Plugin-With-Protocols:
    runs-on: ubuntu-latest
    container: alpine/helm:3.5.4
    env:
      HELM_BIN: echo
      TEST_SCRIPT: |-
        result="$(bin/discover . . . "${path}" | cut -d' ' -f3 | tr , '\n' | sort)"
        test "$expected" == "$result" \
        || (echo "Expected:
        ${expected}
        Result:
        ${result}"; return 1)
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Establish test config hierarchy
        run: sh -c "${SETUP}"

      - name: Test default behaviour
        env:
          path: discover://test
          expected: |-
            test/bar.yml
            test/foo.yaml
        run: sh -c "${TEST_SCRIPT}"

      - name: Test single suffix-based protocol behaviour
        env:
          path: discover://test?suffix_protocol=.txt/test
          expected: test://test/baz.txt
        run: sh -c "${TEST_SCRIPT}"

      - name: Test single suffix-based protocol without suffix filtering behaviour
        env:
          path: discover://test?suffix=&suffix_protocol=.txt/test
          expected: |-
            test/bar.yml
            test/foo.yaml
            test://test/baz.txt
        run: sh -c "${TEST_SCRIPT}"

      - name: Test single suffix-based protocol with other suffix behaviour
        env:
          path: discover://test?recursive&suffix_protocol=.enc/test&suffix=.txt
          expected: |-
            test/baz.txt
            test/one/fizz.txt
            test://test/dir.yaml/foo.enc
        run: sh -c "${TEST_SCRIPT}"

      - name: Test multiple suffix-based protocols behaviour
        env:
          path: discover://test?suffix_protocol=.txt/test&suffix_protocol=.enc/secret&recursive
          expected: |-
            secret://test/dir.yaml/foo.enc
            test://test/baz.txt
            test://test/one/fizz.txt
        run: sh -c "${TEST_SCRIPT}"

      - name: Test restrict single suffix-based protocol with prefix behaviour
        env:
          path: discover://test?recursive&suffix_protocol=.txt/test&prefix=f
          expected: test://test/one/fizz.txt
        run: sh -c "${TEST_SCRIPT}"

      - name: Test single suffix-based protocol unioned with prefix behaviour
        env:
          path: discover://test?union&suffix_protocol=.txt/test&prefix=f
          expected: |-
            test/foo.yaml
            test://test/baz.txt
        run: sh -c "${TEST_SCRIPT}"

      - name: Test single prefix-based protocol behaviour
        # includes implicit suffix filter for .yaml/.yml files
        env:
          path: discover://test?prefix_protocol=b/test
          expected: test://test/bar.yml
        run: sh -c "${TEST_SCRIPT}"

      - name: Test single prefix-based protocol without prefix filtering behaviour
        # includes implicit suffix filter for .yaml/.yml files
        env:
          path: discover://test?prefix=&prefix_protocol=b/test
          expected: |-
            test/foo.yaml
            test://test/bar.yml
        run: sh -c "${TEST_SCRIPT}"

      - name: Test single prefix-based protocol without default suffix filtering behaviour
        env:
          path: discover://test?suffix=&prefix_protocol=b/test
          expected: |-
            test://test/bar.yml
            test://test/baz.txt
        run: sh -c "${TEST_SCRIPT}"

      - name: Test single prefix-based protocol without prefix or suffix filtering behaviour
        env:
          path: discover://test?suffix=&prefix=&prefix_protocol=b/test
          expected: |-
            test/foo.yaml
            test://test/bar.yml
            test://test/baz.txt
        run: sh -c "${TEST_SCRIPT}"

      - name: Test single prefix-based protocol with other prefix behaviour
        env:
          path: discover://test?prefix_protocol=f/test&prefix=b
          expected: |-
            test/bar.yml
            test://test/foo.yaml
        run: sh -c "${TEST_SCRIPT}"

      - name: Test multiple prefix-based protocols behaviour
        env:
          path: discover://test?prefix_protocol=b/test&prefix_protocol=f/secret
          expected: |-
            secret://test/foo.yaml
            test://test/bar.yml
        run: sh -c "${TEST_SCRIPT}"

      - name: Test restrict single prefix-based protocol with suffix behaviour
        env:
          path: discover://test?prefix_protocol=b/test&suffix=.txt
          expected: test://test/baz.txt
        run: sh -c "${TEST_SCRIPT}"

      - name: Test single prefix-based protocol unioned with suffix behaviour
        env:
          path: discover://test?recursive&union&prefix_protocol=baz/test&suffix=.enc
          expected: |-
            test/dir.yaml/foo.enc
            test://test/baz.txt
        run: sh -c "${TEST_SCRIPT}"
