name: Testing
on: [push]
env:
  SETUP: |-
    mkdir -p config/dir.yaml
    mkdir -p config/one/dir.txt

    echo a: 1 > config/foo.yaml
    echo b: 2 > config/bar.yml
    echo c: 3 > config/baz.txt
    echo d: 4 > config/one/foo.yaml
    echo e: 5 > config/one/dir.txt/foo.yaml
    echo f: 6 > config/one/fizz.txt
    echo g: 7 > config/dir.yaml/foo.enc
jobs:
  Test-Downloader-Plugin:
    runs-on: ubuntu-latest
    container: alpine/helm:3.5.4
    env:
      TEST_SCRIPT: |-
        expected=$(printf "---\n# Source: merged-values/templates/values.yaml\n%s" "${expected}")
        result="$(helm template -f "${path}" charts/merged-values)"
        test "$expected" == "$result" || (
          printf "Expected:\n%s\nResult:\n%s\n" "${expected}" "${result}"
          return 1
        )
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Prepare test plugins
        env:
          HELM_PLUGINS: /github/home/.local/share/helm/plugins
        run: |-
          mkdir -p "${HELM_PLUGINS}"
          ln -s "$PWD" "${HELM_PLUGINS}/helm-discover"
          ln -s "${PWD}/test/nester-plugin" "${HELM_PLUGINS}/nester-plugin"
      - name: Establish test config hierarchy
        run: sh -c "${SETUP}"

      - name: Test default behaviour
        env:
          path: discover://config
          expected: |-
            a: 1
            b: 2
        run: sh -c "${TEST_SCRIPT}"

      - name: Test behaviour without default suffix filtering
        env:
          path: discover://config?suffix=
          expected: |-
            a: 1
            b: 2
            c: 3
        run: sh -c "${TEST_SCRIPT}"

      - name: Test recursive behaviour
        env:
          path: discover://config?recursive
          expected: |-
            a: 1
            b: 2
            d: 4
            e: 5
        run: sh -c "${TEST_SCRIPT}"

      - name: Test suffix behaviour
        env:
          path: discover://config?suffix=.txt
          expected: |-
            c: 3
        run: sh -c "${TEST_SCRIPT}"

      - name: Test recursive and suffix behaviour
        env:
          path: discover://config?recursive&suffix=.txt
          expected: |-
            c: 3
            f: 6
        run: sh -c "${TEST_SCRIPT}"

      - name: Test prefix and suffix behaviour
        env:
          path: discover://config?suffix=.txt&prefix=b
          expected: |-
            c: 3
        run: sh -c "${TEST_SCRIPT}"

      - name: Test unioned prefix and suffix behaviour
        env:
          path: discover://config?suffix=.txt&prefix=b&union
          expected: |-
            b: 2
            c: 3
        run: sh -c "${TEST_SCRIPT}"

      - name: Test recursive prefix and suffix behaviour
        env:
          path: discover://config?suffix=.txt&prefix=f&recursive
          expected: |-
            f: 6
        run: sh -c "${TEST_SCRIPT}"

      - name: Test recursive unioned prefix and suffix behaviour
        env:
          path: discover://config?union&suffix=.txt&prefix=f&recursive
          expected: |-
            a: 1
            c: 3
            d: 4
            e: 5
            f: 6
            g: 7
        run: sh -c "${TEST_SCRIPT}"

      - name: Test single suffix-based protocol behaviour
        env:
          path: discover://config?suffix_protocol=.txt/nest
          expected: |-
            nested:
              c: 3
        run: sh -c "${TEST_SCRIPT}"

      - name: Test single suffix-based protocol without suffix filtering behaviour
        env:
          path: discover://config?suffix=&suffix_protocol=.txt/nest
          expected: |-
            a: 1
            b: 2
            nested:
              c: 3
        run: sh -c "${TEST_SCRIPT}"

      - name: Test single suffix-based protocol with other suffix behaviour
        env:
          path: discover://config?recursive&suffix_protocol=.enc/nest&suffix=.txt
          expected: |-
            c: 3
            f: 6
            nested:
              g: 7
        run: sh -c "${TEST_SCRIPT}"

      - name: Test multiple suffix-based protocols behaviour
        env:
          path: discover://config?suffix_protocol=.txt/nest&suffix_protocol=.enc/contain&recursive
          expected: |-
            contained:
              g: 7
            nested:
              c: 3
              f: 6
        run: sh -c "${TEST_SCRIPT}"

      - name: Test restrict single suffix-based protocol with prefix behaviour
        env:
          path: discover://config?recursive&suffix_protocol=.txt/nest&prefix=f
          expected: |-
            nested:
              f: 6
        run: sh -c "${TEST_SCRIPT}"

      - name: Test single suffix-based protocol unioned with prefix behaviour
        env:
          path: discover://config?union&suffix_protocol=.txt/nest&prefix=f
          expected: |-
            a: 1
            nested:
              c: 3
        run: sh -c "${TEST_SCRIPT}"

      - name: Test single prefix-based protocol behaviour
        # includes implicit suffix filter for .yaml/.yml files
        env:
          path: discover://config?prefix_protocol=b/nest
          expected: |-
            nested:
              b: 2
        run: sh -c "${TEST_SCRIPT}"

      - name: Test single prefix-based protocol without prefix filtering behaviour
        # includes implicit suffix filter for .yaml/.yml files
        env:
          path: discover://config?prefix=&prefix_protocol=b/nest
          expected: |-
            a: 1
            nested:
              b: 2
        run: sh -c "${TEST_SCRIPT}"

      - name: Test single prefix-based protocol without default suffix filtering behaviour
        env:
          path: discover://config?suffix=&prefix_protocol=b/nest
          expected: |-
            nested:
              b: 2
              c: 3
        run: sh -c "${TEST_SCRIPT}"

      - name: Test single prefix-based protocol without prefix or suffix filtering behaviour
        env:
          path: discover://config?suffix=&prefix=&prefix_protocol=b/nest
          expected: |-
            a: 1
            nested:
              b: 2
              c: 3
        run: sh -c "${TEST_SCRIPT}"

      - name: Test single prefix-based protocol with other prefix behaviour
        env:
          path: discover://config?prefix_protocol=f/nest&prefix=b
          expected: |-
            b: 2
            nested:
              a: 1
        run: sh -c "${TEST_SCRIPT}"

      - name: Test multiple prefix-based protocols behaviour
        env:
          path: discover://config?prefix_protocol=b/nest&prefix_protocol=f/contain
          expected: |-
            contained:
              a: 1
            nested:
              b: 2
        run: sh -c "${TEST_SCRIPT}"

      - name: Test restrict single prefix-based protocol with suffix behaviour
        env:
          path: discover://config?prefix_protocol=b/nest&suffix=.txt
          expected: |-
            nested:
              c: 3
        run: sh -c "${TEST_SCRIPT}"

      - name: Test single prefix-based protocol unioned with suffix behaviour
        env:
          path: discover://config?recursive&union&prefix_protocol=baz/nest&suffix=.enc
          expected: |-
            g: 7
            nested:
              c: 3
        run: sh -c "${TEST_SCRIPT}"
